
global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_smarthost: '10.1.1.128:25'
  smtp_from: 'ci@literatumonline.com'
  smtp_require_tls: false

route:
  receiver: annotator
  repeat_interval: 24h
  group_wait: 1s
  group_interval: 1s
  group_by: ['...'] 
  

receivers:
  - name: 'annotator'
    webhook_configs:
      - url: 'http://192.168.2.9:5000'
        send_resolved: true