global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 15s
  external_labels:
    env: ubuntu
    servers_group: stani

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.2.9:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 10s
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'node_exporter'
  scrape_interval: 30s
  static_configs:
    - targets: ['192.168.2.9:9100']

- job_name: 'annotator_receiver'
  scrape_interval: 10s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['192.168.2.9:5000']

- job_name: 'annotator_server'
  scrape_interval: 10s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['192.168.2.9:5001']